from pydantic import BaseModel, Field
from typing import List, Optional
import time
from app.shared.enums import ProviderType
from app.ai.contracts.message import Message
from app.ai.contracts.usage import TokenUsage


class ProviderInfo(BaseModel):
    provider: ProviderType = Field(..., description="The executing AI provider name")
    model: str = Field(..., description="The specific provider model version executed")


class AIResponse(BaseModel):
    id: str = Field(..., description="Unique generated generation transaction trace identifier")
    object: str = Field("ai.response", description="Object descriptor")
    created: int = Field(default_factory=lambda: int(time.time()), description="Epoch transaction creation timestamp")
    messages: List[Message] = Field(..., description="Choice messages generated by the provider model")
    usage: Optional[TokenUsage] = Field(None, description="Detailed token utilization stats")
    provider_info: Optional[ProviderInfo] = Field(None, description="Information indicating executing model and provider")
